### PR TITLE
Update for PyPNG 0.20220715.0

### LINKED ISSUE #1: Maintainer is switching to GitLab
### Comment:

Hi, i am the maintainer of the PyPNG package. I don't really do conda or conda-forge. However

- i am moving development to GitLab https://gitlab.com/drj11/pypng
- i am considering not using PyPI for future releases.

So, how do you feel about drawing sources from GitLab?

A gentle start would be to bump to PyPNG 0.0.21 (release August 2021). I'm happy to submit a PR, if you're happy to provide a bit of guidance.

### PR DESCRIPTION
**Pull request by drj11**
Closes #3  
Closes #1 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by drj11** [comment]
This is my attempt at updating for PyPNG 0.0.21

How do conda-forge's builds for different PyPNG versions work?

On PyPI the source tarball is at a location that can be predicted from the version.

But i have moved (experimentally, i might add) to using GitLab's package index: https://gitlab.com/drj11/pypng/-/packages which has download URLs that are not predictable. Do I just bump the version, URL, and SHA for each PyPNG version?

**Comment by drj11** [comment]
hey @conda-forge-linter do you have a link to the spec?

**Comment by drj11** [comment]
thanks @conda-forge-linter, hope it's worth it

**Comment by drj11** [comment]
@conda-forge-admin, please rerender

**Comment by drj11** [comment]
The azure pipelines are failing because ubuntu-16.04 is the requested image. This is specified in the file `.azure-pipelines/azure-pipelines-linux.yml`.

But _that_ file says

```
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
```

I had a quick look, but it's not clear to me how to proceed to fix the azure thing. [later: oh i see the rerender fixes some of that]

**Comment by drj11** [comment]
As far as i can tell, this is good to review @hmaarrfk 
It's been quite emotional so far.

**Comment by hmaarrfk** [comment]
I'll take a look  in a bit. You did great!

**Comment by hmaarrfk** [comment]
I went to your tags and downloaded the appropriate tag. then copied the url

Adjusted as necessary.

**Comment by hmaarrfk** [comment]
In your original issue, you said "I don't really do conda or conda-forge."

How do you plan to release?

If you want to add yourself as a maintainer, then feel free to do so with the command:

https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username

**Review by hmaarrfk — APPROVED** [review]

**Comment by hmaarrfk** [comment]
As for the spec, this is likely the best spec
https://github.com/conda-forge/staged-recipes/blob/main/recipes/example/meta.yaml

**Pull request merged**
